version: '3'
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        - OUTPUT_BINARY=${OUTPUT_BINARY}
        - BUILD_DIR=${BUILD_DIR}
    environment:
      - OUTPUT_BINARY=${OUTPUT_BINARY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
